/**
 * @file src/utils/ns/Enums.ts
 */
export { 
    VendorCategoryEnum, CustomerStatusEnum, AccountTypeEnum,
    CustomerTaxItemEnum, ContactRoleEnum, SubrecordTypeEnum, 
    EntityRecordTypeEnum, NetSuiteRecordTypeEnum, RecordTypeEnum, 
    LeadSourceEnum, LeadStatusEnum, SalesOrderStatusEnum 
} from './record';
export { AccountEnvironmentEnum, ScriptTypeEnum } from './SuiteScriptEnvironment';
export { 
    FilterOperatorEnum, SearchSortEnum, DateOperatorEnum, TextOperatorEnum, 
    ColumnSummaryEnum, RecordOperatorEnum, SearchOperatorEnum, NumericOperatorEnum, 
    MultiSelectOperatorEnum
} from './search'
export { NetSuiteFileTypeEnum, NetSuiteFileEncodingEnum } from './File';
/**
 * @enum {string} **`UnitsTypeEnum`**
 * @description Enum for unit types in NetSuite. (defined by account user)
 * @property {string} QUANTITY - Quantity unit type.
 * @property {string} WEIGHT - Weight unit type.
 * @property {string} LENGTH - Length unit type.
 * @property {string} VOLUME - Volume unit type.
 * @property {string} TIME - Time unit type.
 */
export enum UnitsTypeEnum {
    QUANTITY = "Quantity",
    WEIGHT = "Weight",
    LENGTH = "Length",
    VOLUME = "Volume",
    TIME = "Time",
}

/**
 * @enum {string} **`UnitsEnum`**
 * @description Enum for unit types in NetSuite. (defined by account user)
 * @property {string} EACH - Each unit.
 * @property {string} DOZEN - Dozen unit.
 * @property {string} GRAMS - Grams unit.
 * @property {string} KILOGRAMS - Kilograms unit.
 * @property {string} MILLIGRAMS - Milligrams unit.
 * @property {string} LITERS - Liters unit.
 * @property {string} MILLILITERS - Milliliters unit.
 * @property {string} GALLONS - Gallons unit.
 * @property {string} POUNDS - Pounds unit.
 * @property {string} METERS - Meters unit.
 * @property {string} INCHES - Inches unit.
 * @property {string} FEET - Feet unit.
 */
export enum UnitsEnum {
    EACH = "each",
    DOZEN = "dozen",
    GRAMS = "grams",
    KILOGRAMS = "kilograms",
    MILLIGRAMS = "milligrams",
    LITERS = "liters",
    MILLILITERS = "milliliters",
    GALLONS = "gallons",
    POUNDS = "pounds",
    METERS = "meters",
    INCHES = "inches",
    FEET = "feet",
}

/**
 * @enum {string} **`EmailPreferenceEnum`**
 * @description Enum for email file attachment preferences in NetSuite.
 * @property {string} HTML - HTML format.
 * @property {string} PDF - PDF format.
 */
export enum EmailPreferenceEnum {
    HTML = "_HTML",
    PDF = "_PDF",
}
/**
 * @enum {string} **`GlobalSubscriptionStatusEnum`**
 * @description Enum for global subscription status in NetSuite.
 * @reference https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2024_2/schema/enum/globalsubscriptionstatus.html?mode=package
 * @property {string} CONFIRMED_OPT_IN - Confirmed Opt In
 * @property {string} CONFIRMED_OPT_OUT - Confirmed Opt Out
 * @property {string} SOFT_OPT_IN - Soft Opt In
 * @property {string} SOFT_OPT_OUT - Soft Opt Out
 */
export enum GlobalSubscriptionStatusEnum {
    CONFIRMED_OPT_IN = "_confirmedOptIn",
    CONFIRMED_OPT_OUT = "_confirmedOptOut",
    SOFT_OPT_IN = "_softOptIn",
    SOFT_OPT_OUT = "_softOptOut",
}


/**
 * @reference https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2024_2/schema/enum/itemsource.html?mode=package
 * - Namespace: urn:types.common.platform.webservices.netsuite.com
 * @enum {string} **`ItemSourceEnum`**
 * @description Enum for item source types in NetSuite.
 * @property {string} STOCK - Represents stock items.
 * @property {string} PHANTOM - Represents phantom items.
 * @property {string} WORK_ORDER - Represents work order items.
 * @property {string} PURCHASE_ORDER - Represents purchase order items.
 */
export enum ItemSourceEnum {
    STOCK = "_stock",
    PHANTOM = "_phantom",
    WORK_ORDER = "_workOrder",
    PURCHASE_ORDER = "_purchaseOrder"
}



/**
 * @reference https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2024_2/schema/enum/country.html?mode=package
 * - Namespace: urn:types.common.platform.webservices.netsuite.com
 * @enum {string} **`NetSuiteCountryEnum`**
 * @description Enum for country field in NetSuite records.
 * @property {string} AFGHANISTAN - Afghanistan
 * @property {string} UNITED_STATES - United States
 * @property {string} CANADA - Canada
 * @property {string} CHINA - China
 * @property {string} HONG_KONG - Hong Kong
 * @property {string} IRAQ - Iraq
 * @property {string} JAPAN - Japan
 * @property {string} SOUTH_KOREA - South Korea
 * @more ...
 */
export enum NetSuiteCountryEnum {
    AFGHANISTAN = "_afghanistan",
    ALAND_ISLANDS = "_alandIslands",
    ALBANIA = "_albania",
    ALGERIA = "_algeria",
    AMERICAN_SAMOA = "_americanSamoa",
    ANDORRA = "_andorra",
    ANGOLA = "_angola",
    ANGUILLA = "_anguilla",
    ANTARCTICA = "_antarctica",
    ANTIGUA_AND_BARBUDA = "_antiguaAndBarbuda",
    ARGENTINA = "_argentina",
    ARMENIA = "_armenia",
    ARUBA = "_aruba",
    AUSTRALIA = "_australia",
    AUSTRIA = "_austria",
    AZERBAIJAN = "_azerbaijan",
    BAHAMAS = "_bahamas",
    BAHRAIN = "_bahrain",
    BANGLADESH = "_bangladesh",
    BARBADOS = "_barbados",
    BELARUS = "_belarus",
    BELGIUM = "_belgium",
    BELIZE = "_belize",
    BENIN = "_benin",
    BERMUDA = "_bermuda",
    BHUTAN = "_bhutan",
    BOLIVIA = "_boliviaPlurinationalStateOf",
    BONAIRE_SINT_EUSTATIUS_AND_SABA = "_bonaireSintEustatiusAndSaba",
    BOSNIA_AND_HERZEGOVINA = "_bosniaAndHerzegovina",
    BOTSWANA = "_botswana",
    BOUVET_ISLAND = "_bouvetIsland",
    BRAZIL = "_brazil",
    BRITISH_INDIAN_OCEAN_TERRITORY = "_britishIndianOceanTerritory",
    BRUNEI_DARUSSALAM = "_bruneiDarussalam",
    BULGARIA = "_bulgaria",
    BURKINA_FASO = "_burkinaFaso",
    BURUNDI = "_burundi",
    CABO_VERDE = "_caboVerde",
    CAMBODIA = "_cambodia",
    CAMEROON = "_cameroon",
    CANADA = "_canada",
    CANARY_ISLANDS = "_canaryIslands",
    CAYMAN_ISLANDS = "_caymanIslands",
    CENTRAL_AFRICAN_REPUBLIC = "_centralAfricanRepublic",
    CEUTA_AND_MELILLA = "_ceutaAndMelilla",
    CHAD = "_chad",
    CHILE = "_chile",
    CHINA = "_china",
    CHRISTMAS_ISLAND = "_christmasIsland",
    COCOS_KEELING_ISLANDS = "_cocosKeelingIslands",
    COLOMBIA = "_colombia",
    COMOROS = "_comoros",
    CONGO = "_congo",
    CONGO_DEMOCRATIC_REPUBLIC = "_congoTheDemocraticRepublicOfThe",
    COOK_ISLANDS = "_cookIslands",
    COSTA_RICA = "_costaRica",
    COTE_DIVOIRE = "_coteDIvoire",
    CROATIA = "_croatia",
    CUBA = "_cuba",
    CURACAO = "_curacao",
    CYPRUS = "_cyprus",
    CZECHIA = "_czechia",
    DENMARK = "_denmark",
    DJIBOUTI = "_djibouti",
    DOMINICA = "_dominica",
    DOMINICAN_REPUBLIC = "_dominicanRepublic",
    ECUADOR = "_ecuador",
    EGYPT = "_egypt",
    EL_SALVADOR = "_elSalvador",
    EQUATORIAL_GUINEA = "_equatorialGuinea",
    ERITREA = "_eritrea",
    ESTONIA = "_estonia",
    ESWATINI = "_eswatini",
    ETHIOPIA = "_ethiopia",
    FALKLAND_ISLANDS = "_falklandIslandsMalvinas",
    FAROE_ISLANDS = "_faroeIslands",
    FIJI = "_fiji",
    FINLAND = "_finland",
    FRANCE = "_france",
    FRENCH_GUIANA = "_frenchGuiana",
    FRENCH_POLYNESIA = "_frenchPolynesia",
    FRENCH_SOUTHERN_TERRITORIES = "_frenchSouthernTerritories",
    GABON = "_gabon",
    GAMBIA = "_gambia",
    GEORGIA = "_georgia",
    GERMANY = "_germany",
    GHANA = "_ghana",
    GIBRALTAR = "_gibraltar",
    GREECE = "_greece",
    GREENLAND = "_greenland",
    GRENADA = "_grenada",
    GUADELOUPE = "_guadeloupe",
    GUAM = "_guam",
    GUATEMALA = "_guatemala",
    GUERNSEY = "_guernsey",
    GUINEA = "_guinea",
    GUINEA_BISSAU = "_guineaBissau",
    GUYANA = "_guyana",
    HAITI = "_haiti",
    HEARD_ISLAND_AND_MCDONALD_ISLANDS = "_heardIslandAndMcdonaldIslands",
    HOLY_SEE = "_holySee",
    HONDURAS = "_honduras",
    HONG_KONG = "_hongKong",
    HUNGARY = "_hungary",
    ICELAND = "_iceland",
    INDIA = "_india",
    INDONESIA = "_indonesia",
    IRAN = "_iranIslamicRepublicOf",
    IRAQ = "_iraq",
    IRELAND = "_ireland",
    ISLE_OF_MAN = "_isleOfMan",
    ISRAEL = "_israel",
    ITALY = "_italy",
    JAMAICA = "_jamaica",
    JAPAN = "_japan",
    JERSEY = "_jersey",
    JORDAN = "_jordan",
    KAZAKHSTAN = "_kazakhstan",
    KENYA = "_kenya",
    KIRIBATI = "_kiribati",
    NORTH_KOREA = "_koreaTheDemocraticPeoplesRepublicOf",
    SOUTH_KOREA = "_koreaTheRepublicOf",
    KOSOVO = "_kosovo",
    KUWAIT = "_kuwait",
    KYRGYZSTAN = "_kyrgyzstan",
    LAO = "_laoPeoplesDemocraticRepublic",
    LATVIA = "_latvia",
    LEBANON = "_lebanon",
    LESOTHO = "_lesotho",
    LIBERIA = "_liberia",
    LIBYA = "_libya",
    LIECHTENSTEIN = "_liechtenstein",
    LITHUANIA = "_lithuania",
    LUXEMBOURG = "_luxembourg",
    MACAO = "_macao",
    MADAGASCAR = "_madagascar",
    MALAWI = "_malawi",
    MALAYSIA = "_malaysia",
    MALDIVES = "_maldives",
    MALI = "_mali",
    MALTA = "_malta",
    MARSHALL_ISLANDS = "_marshallIslands",
    MARTINIQUE = "_martinique",
    MAURITANIA = "_mauritania",
    MAURITIUS = "_mauritius",
    MAYOTTE = "_mayotte",
    MEXICO = "_mexico",
    MICRONESIA = "_micronesiaFederatedStatesOf",
    MOLDOVA = "_moldovaTheRepublicOf",
    MONACO = "_monaco",
    MONGOLIA = "_mongolia",
    MONTENEGRO = "_montenegro",
    MONTSERRAT = "_montserrat",
    MOROCCO = "_morocco",
    MOZAMBIQUE = "_mozambique",
    MYANMAR = "_myanmar",
    NAMIBIA = "_namibia",
    NAURU = "_nauru",
    NEPAL = "_nepal",
    NETHERLANDS = "_netherlands",
    NEW_CALEDONIA = "_newCaledonia",
    NEW_ZEALAND = "_newZealand",
    NICARAGUA = "_nicaragua",
    NIGER = "_niger",
    NIGERIA = "_nigeria",
    NIUE = "_niue",
    NORFOLK_ISLAND = "_norfolkIsland",
    NORTHERN_MARIANA_ISLANDS = "_northernMarianaIslands",
    NORTH_MACEDONIA = "_northMacedonia",
    NORWAY = "_norway",
    OMAN = "_oman",
    PAKISTAN = "_pakistan",
    PALAU = "_palau",
    PALESTINE = "_palestineStateOf",
    PANAMA = "_panama",
    PAPUA_NEW_GUINEA = "_papuaNewGuinea",
    PARAGUAY = "_paraguay",
    PERU = "_peru",
    PHILIPPINES = "_philippines",
    PITCAIRN = "_pitcairn",
    POLAND = "_poland",
    PORTUGAL = "_portugal",
    PUERTO_RICO = "_puertoRico",
    QATAR = "_qatar",
    REUNION = "_reunion",
    ROMANIA = "_romania",
    RUSSIAN_FEDERATION = "_russianFederation",
    RWANDA = "_rwanda",
    SAINT_BARTHELEMY = "_saintBarthelemy",
    SAINT_HELENA = "_saintHelenaAscensionAndTristanDaCunha",
    SAINT_KITTS_AND_NEVIS = "_saintKittsAndNevis",
    SAINT_LUCIA = "_saintLucia",
    SAINT_MARTIN = "_saintMartinFrenchPart",
    SAINT_PIERRE_AND_MIQUELON = "_saintPierreAndMiquelon",
    SAINT_VINCENT_AND_GRENADINES = "_saintVincentAndTheGrenadines",
    SAMOA = "_samoa",
    SAN_MARINO = "_sanMarino",
    SAO_TOME_AND_PRINCIPE = "_saoTomeAndPrincipe",
    SAUDI_ARABIA = "_saudiArabia",
    SENEGAL = "_senegal",
    SERBIA = "_serbia",
    SEYCHELLES = "_seychelles",
    SIERRA_LEONE = "_sierraLeone",
    SINGAPORE = "_singapore",
    SINT_MAARTEN = "_sintMaartenDutchPart",
    SLOVAKIA = "_slovakia",
    SLOVENIA = "_slovenia",
    SOLOMON_ISLANDS = "_solomonIslands",
    SOMALIA = "_somalia",
    SOUTH_AFRICA = "_southAfrica",
    SOUTH_GEORGIA = "_southGeorgiaAndTheSouthSandwichIslands",
    SOUTH_SUDAN = "_southSudan",
    SPAIN = "_spain",
    SRI_LANKA = "_sriLanka",
    SUDAN = "_sudan",
    SURINAME = "_suriname",
    SVALBARD_AND_JAN_MAYEN = "_svalbardAndJanMayen",
    SWEDEN = "_sweden",
    SWITZERLAND = "_switzerland",
    SYRIA = "_syrianArabRepublic",
    TAIWAN = "_taiwan",
    TAJIKISTAN = "_tajikistan",
    TANZANIA = "_tanzaniaTheUnitedRepublicOf",
    THAILAND = "_thailand",
    TIMOR_LESTE = "_timorLeste",
    TOGO = "_togo",
    TOKELAU = "_tokelau",
    TONGA = "_tonga",
    TRINIDAD_AND_TOBAGO = "_trinidadAndTobago",
    TUNISIA = "_tunisia",
    TURKIYE = "_turkiye",
    TURKMENISTAN = "_turkmenistan",
    TURKS_AND_CAICOS_ISLANDS = "_turksAndCaicosIslands",
    TUVALU = "_tuvalu",
    UGANDA = "_uganda",
    UKRAINE = "_ukraine",
    UNITED_ARAB_EMIRATES = "_unitedArabEmirates",
    UNITED_KINGDOM = "_unitedKingdom",
    UNITED_STATES = "_unitedStates",
    UNITED_STATES_MINOR_OUTLYING_ISLANDS = "_unitedStatesMinorOutlyingIslands",
    URUGUAY = "_uruguay",
    UZBEKISTAN = "_uzbekistan",
    VANUATU = "_vanuatu",
    VENEZUELA = "_venezuelaBolivarianRepublicOf",
    VIETNAM = "_vietNam",
    VIRGIN_ISLANDS_BRITISH = "_virginIslandsBritish",
    VIRGIN_ISLANDS_US = "_virginIslandsUS",
    WALLIS_AND_FUTUNA = "_wallisAndFutunaIslands",
    WESTERN_SAHARA = "_westernSahara",
    YEMEN = "_yemen",
    ZAMBIA = "_zambia",
    ZIMBABWE = "_zimbabwe"
}

/**
 * @enum {string} **`CountryAbbreviationEnum`**
 * @description Enum for country two letter abbreviation codes (ISO 3166-1 alpha-2)
 * @reference 
 * - {@link https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_4267255811.html#bridgehead_4447485621\}
 * - {@link https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes}
 * @property {string} AFGHANISTAN - AF
 * @property {string} UNITED_STATES - US
 * @property {string} CANADA - CA
 * @property {string} CHINA - CN
 * @property {string} HONG_KONG - HK
 * @property {string} IRAQ - IQ
 * @property {string} JAPAN - JP
 * @property {string} SOUTH_KOREA - KR
 */
export enum CountryAbbreviationEnum {
    AFGHANISTAN = "AF",
    ALAND_ISLANDS = "AX",
    ALBANIA = "AL",
    ALGERIA = "DZ",
    AMERICAN_SAMOA = "AS",
    ANDORRA = "AD",
    ANGOLA = "AO",
    ANGUILLA = "AI",
    ANTARCTICA = "AQ",
    ANTIGUA_AND_BARBUDA = "AG",
    ARGENTINA = "AR",
    ARMENIA = "AM",
    ARUBA = "AW",
    AUSTRALIA = "AU",
    AUSTRIA = "AT",
    AZERBAIJAN = "AZ",
    BAHAMAS = "BS",
    BAHRAIN = "BH",
    BANGLADESH = "BD",
    BARBADOS = "BB",
    BELARUS = "BY",
    BELGIUM = "BE",
    BELIZE = "BZ",
    BENIN = "BJ",
    BERMUDA = "BM",
    BHUTAN = "BT",
    BOLIVIA = "BO",
    BONAIRE_SINT_EUSTATIUS_AND_SABA = "BQ",
    BOSNIA_AND_HERZEGOVINA = "BA",
    BOTSWANA = "BW",
    BOUVET_ISLAND = "BV",
    BRAZIL = "BR",
    BRITISH_INDIAN_OCEAN_TERRITORY = "IO",
    BRUNEI_DARUSSALAM = "BN",
    BULGARIA = "BG",
    BURKINA_FASO = "BF",
    BURUNDI = "BI",
    CABO_VERDE = "CV",
    CAMBODIA = "KH",
    CAMEROON = "CM",
    CANADA = "CA",
    CANARY_ISLANDS = "IC",
    CAYMAN_ISLANDS = "KY",
    CENTRAL_AFRICAN_REPUBLIC = "CF",
    CEUTA_AND_MELILLA = "EA",
    CHAD = "TD",
    CHILE = "CL",
    CHINA = "CN",
    CHRISTMAS_ISLAND = "CX",
    COCOS_KEELING_ISLANDS = "CC",
    COLOMBIA = "CO",
    COMOROS = "KM",
    CONGO = "CG",
    CONGO_DEMOCRATIC_REPUBLIC = "CD",
    COOK_ISLANDS = "CK",
    COSTA_RICA = "CR",
    COTE_DIVOIRE = "CI",
    CROATIA = "HR",
    CUBA = "CU",
    CURACAO = "CW",
    CYPRUS = "CY",
    CZECHIA = "CZ",
    DENMARK = "DK",
    DJIBOUTI = "DJ",
    DOMINICA = "DM",
    DOMINICAN_REPUBLIC = "DO",
    ECUADOR = "EC",
    EGYPT = "EG",
    EL_SALVADOR = "SV",
    EQUATORIAL_GUINEA = "GQ",
    ERITREA = "ER",
    ESTONIA = "EE",
    ESWATINI = "SZ",
    ETHIOPIA = "ET",
    FALKLAND_ISLANDS = "FK",
    FAROE_ISLANDS = "FO",
    FIJI = "FJ",
    FINLAND = "FI",
    FRANCE = "FR",
    FRENCH_GUIANA = "GF",
    FRENCH_POLYNESIA = "PF",
    FRENCH_SOUTHERN_TERRITORIES = "TF",
    GABON = "GA",
    GAMBIA = "GM",
    GEORGIA = "GE",
    GERMANY = "DE",
    GHANA = "GH",
    GIBRALTAR = "GI",
    GREECE = "GR",
    GREENLAND = "GL",
    GRENADA = "GD",
    GUADELOUPE = "GP",
    GUAM = "GU",
    GUATEMALA = "GT",
    GUERNSEY = "GG",
    GUINEA = "GN",
    GUINEA_BISSAU = "GW",
    GUYANA = "GY",
    HAITI = "HT",
    HEARD_ISLAND_AND_MCDONALD_ISLANDS = "HM",
    HOLY_SEE = "VA",
    HONDURAS = "HN",
    HONG_KONG = "HK",
    HUNGARY = "HU",
    ICELAND = "IS",
    INDIA = "IN",
    INDONESIA = "ID",
    IRAN = "IR",
    IRAQ = "IQ",
    IRELAND = "IE",
    ISLE_OF_MAN = "IM",
    ISRAEL = "IL",
    ITALY = "IT",
    JAMAICA = "JM",
    JAPAN = "JP",
    JERSEY = "JE",
    JORDAN = "JO",
    KAZAKHSTAN = "KZ",
    KENYA = "KE",
    KIRIBATI = "KI",
    NORTH_KOREA = "KP",
    SOUTH_KOREA = "KR",
    KOSOVO = "XK",
    KUWAIT = "KW",
    KYRGYZSTAN = "KG",
    LAO = "LA",
    LATVIA = "LV",
    LEBANON = "LB",
    LESOTHO = "LS",
    LIBERIA = "LR",
    LIBYA = "LY",
    LIECHTENSTEIN = "LI",
    LITHUANIA = "LT",
    LUXEMBOURG = "LU",
    MACAO = "MO",
    MADAGASCAR = "MG",
    MALAWI = "MW",
    MALAYSIA = "MY",
    MALDIVES = "MV",
    MALI = "ML",
    MALTA = "MT",
    MARSHALL_ISLANDS = "MH",
    MARTINIQUE = "MQ",
    MAURITANIA = "MR",
    MAURITIUS = "MU",
    MAYOTTE = "YT",
    MEXICO = "MX",
    MICRONESIA = "FM",
    MOLDOVA = "MD",
    MONACO = "MC",
    MONGOLIA = "MN",
    MONTENEGRO = "ME",
    MONTSERRAT = "MS",
    MOROCCO = "MA",
    MOZAMBIQUE = "MZ",
    MYANMAR = "MM",
    NAMIBIA = "NA",
    NAURU = "NR",
    NEPAL = "NP",
    NETHERLANDS = "NL",
    NEW_CALEDONIA = "NC",
    NEW_ZEALAND = "NZ",
    NICARAGUA = "NI",
    NIGER = "NE",
    NIGERIA = "NG",
    NIUE = "NU",
    NORFOLK_ISLAND = "NF",
    NORTHERN_MARIANA_ISLANDS = "MP",
    NORTH_MACEDONIA = "MK",
    NORWAY = "NO",
    OMAN = "OM",
    PAKISTAN = "PK",
    PALAU = "PW",
    PALESTINE = "PS",
    PANAMA = "PA",
    PAPUA_NEW_GUINEA = "PG",
    PARAGUAY = "PY",
    PERU = "PE",
    PHILIPPINES = "PH",
    PITCAIRN = "PN",
    POLAND = "PL",
    PORTUGAL = "PT",
    PUERTO_RICO = "PR",
    QATAR = "QA",
    REUNION = "RE",
    ROMANIA = "RO",
    RUSSIAN_FEDERATION = "RU",
    RWANDA = "RW",
    SAINT_BARTHELEMY = "BL",
    SAINT_HELENA = "SH",
    SAINT_KITTS_AND_NEVIS = "KN",
    SAINT_LUCIA = "LC",
    SAINT_MARTIN = "MF",
    SAINT_PIERRE_AND_MIQUELON = "PM",
    SAINT_VINCENT_AND_GRENADINES = "VC",
    SAMOA = "WS",
    SAN_MARINO = "SM",
    SAO_TOME_AND_PRINCIPE = "ST",
    SAUDI_ARABIA = "SA",
    SENEGAL = "SN",
    SERBIA = "RS",
    SEYCHELLES = "SC",
    SIERRA_LEONE = "SL",
    SINGAPORE = "SG",
    SINT_MAARTEN = "SX",
    SLOVAKIA = "SK",
    SLOVENIA = "SI",
    SOLOMON_ISLANDS = "SB",
    SOMALIA = "SO",
    SOUTH_AFRICA = "ZA",
    SOUTH_GEORGIA = "GS",
    SOUTH_SUDAN = "SS",
    SPAIN = "ES",
    SRI_LANKA = "LK",
    SUDAN = "SD",
    SURINAME = "SR",
    SVALBARD_AND_JAN_MAYEN = "SJ",
    SWEDEN = "SE",
    SWITZERLAND = "CH",
    SYRIA = "SY",
    TAIWAN = "TW",
    TAJIKISTAN = "TJ",
    TANZANIA = "TZ",
    THAILAND = "TH",
    TIMOR_LESTE = "TL",
    TOGO = "TG",
    TOKELAU = "TK",
    TONGA = "TO",
    TRINIDAD_AND_TOBAGO = "TT",
    TUNISIA = "TN",
    TURKIYE = "TR",
    TURKMENISTAN = "TM",
    TURKS_AND_CAICOS_ISLANDS = "TC",
    TUVALU = "TV",
    UGANDA = "UG",
    UKRAINE = "UA",
    UNITED_ARAB_EMIRATES = "AE",
    UNITED_KINGDOM = "GB",
    UNITED_STATES = "US",
    UNITED_STATES_MINOR_OUTLYING_ISLANDS = "UM",
    URUGUAY = "UY",
    UZBEKISTAN = "UZ",
    VANUATU = "VU",
    VENEZUELA = "VE",
    VIETNAM = "VN",
    VIRGIN_ISLANDS_BRITISH = "VG",
    VIRGIN_ISLANDS_US = "VI",
    WALLIS_AND_FUTUNA = "WF",
    WESTERN_SAHARA = "EH",
    YEMEN = "YE",
    ZAMBIA = "ZM",
    ZIMBABWE = "ZW"
}


/**
 * @enum {string} **`StateAbbreviationEnum`**
 * @description Enum for US states and territories two letter abbreviations
 * @property {string} CALIFORNIA - CA
 * @more ...
 */
export enum StateAbbreviationEnum {
    ALABAMA = "AL",
    ALASKA = "AK",
    AMERICAN_SAMOA = "AS",
    ARIZONA = "AZ",
    ARKANSAS = "AR",
    CALIFORNIA = "CA",
    COLORADO = "CO",
    CONNECTICUT = "CT",
    DELAWARE = "DE",
    DISTRICT_OF_COLUMBIA = "DC",
    FEDERATED_STATES_OF_MICRONESIA = "FM",
    FLORIDA = "FL",
    GEORGIA = "GA",
    GUAM = "GU",
    HAWAII = "HI",
    IDAHO = "ID",
    ILLINOIS = "IL",
    INDIANA = "IN",
    IOWA = "IA",
    KANSAS = "KS",
    KENTUCKY = "KY",
    LOUISIANA = "LA",
    MAINE = "ME",
    MARSHALL_ISLANDS = "MH",
    MARYLAND = "MD",
    MASSACHUSETTS = "MA",
    MICHIGAN = "MI",
    MINNESOTA = "MN",
    MISSISSIPPI = "MS",
    MISSOURI = "MO",
    MONTANA = "MT",
    NEBRASKA = "NE",
    NEVADA = "NV",
    NEW_HAMPSHIRE = "NH",
    NEW_JERSEY = "NJ",
    NEW_MEXICO = "NM",
    NEW_YORK = "NY",
    NORTH_CAROLINA = "NC",
    NORTH_DAKOTA = "ND",
    NORTHERN_MARIANA_ISLANDS = "MP",
    OHIO = "OH",
    OKLAHOMA = "OK",
    OREGON = "OR",
    PALAU = "PW",
    PENNSYLVANIA = "PA",
    PUERTO_RICO = "PR",
    RHODE_ISLAND = "RI",
    SOUTH_CAROLINA = "SC",
    SOUTH_DAKOTA = "SD",
    TENNESSEE = "TN",
    TEXAS = "TX",
    TRUST_TERRITORIES_OF_THE_PACIFIC_ISLANDS = "TT",
    UTAH = "UT",
    VERMONT = "VT",
    VIRGIN_ISLANDS = "VI",
    VIRGINIA = "VA",
    WASHINGTON = "WA",
    WEST_VIRGINIA = "WV",
    WISCONSIN = "WI",
    WYOMING = "WY"
}